### ISSUE TITLE
Allow user to select water agency

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/BillCalculator#3]
After the app is calculating rates using RateParser (#2) we will want the user to be able to select the water agency corresponding to where they live. As a first pass this should be a dropdown or autocomplete field to type in the name of a water district directly. We can then get the most recent rate information for that district and calculate the bill.

- [x] Add selection element for user to specify district
- [ ] Capture chosen district information and retrieve most recent OWRS information for this district
- [x] Calculate water bill using the OWRS file for the specified district (This might include altering other available inputs?)

**Comment by emmalin16** [comment]
@christophertull Thank you for the comments! 
We will move on to issue #3. I am wondering that where shall we retrieve the most recent OWRS information for different districts. Is it from the folder of Open-Water-Rate-Specification/full_utility_rates/California?
Thank you!

**Comment by christophertull** [comment]
Yes, exactly. For now we will just uses the files in that repo

**Comment by emmalin16** [comment]
@christophertull I just uploaded the preliminary results of adding the selection element to specify district. I haven't included all the district files, just added a few in this version. I can also use ggmap package to get lat/lons of the input address (haven't included the output of lat/lons in this version). Please let me know if you have any comments or suggestions about it.

I have a question about mapping lat/lon to water district. I am not quite sure about how the water district is defined. Do you have any advice on this part? Is there a shapefile of water districts or anything else to help us map lat/lon? 

Thank you!

**Comment by christophertull** [comment]
Awesome! That's great to hear. I will take a look when I get a chance.

Yes, we have a shapefile of water district boundaries that I will send to you. The boundaries are not perfect, but they pretty accurate for most of the major water retailers. 

There will be an intermediate step to join the retailer names in the shapefile with the retailer names in the OWRS files because sometimes they won't exactly match. Fortunately we have another former CUSPie who has worked on this fuzzy matching so I can get you a file to map between the two names.

**Comment by emmalin16** [comment]
Got it! Thank you!

**Comment by christophertull** [comment]
I will send the data for you guys soon when I get back from lunch. For now I noticed that you have commited all the OWRS files to the repo. I would not encourage this because it bloats the repo and we already have these files tracked in a different repo so I do not want to encourage duplication.

I have removed the OWRS files from the repo and added `BillCalculator_RateParser/California/*` to the .gitignore file to ignore them in the future.

**Comment by christophertull** [comment]
Very nice! I did some testing and it looks really good so far. Some minor suggestions for changes:

- [x] Move the selection of the water district and the address up to the top of the other inputs.
- [x] Require either a district OR an address. We should not need both. The address is mostly for users who do not know which district they have.
- [x] The text for the "Customer Class" input box is bold, but the others are not. They should all be consistent. 

More broadly, I would suggest working on solidifying the current task before moving on to the spatial lookup of the water district. For example, the OWRS file paths still seem to be hardcoded (in the `fnAddress ` function). It would be preferable to look up all the OWRS files, populate the Water District dropdown from that list, and then use the user selection to look up the proper OWRS file rather than hardcoding it.

**Comment by christophertull** [comment]
Also, when you do eventually get to the spatial joining, you can download the utility boundaries from here: https://argo-labs.carto.com/u/california-data-collaborative/tables/supplier_status_table/public?redirected=true

**Comment by emmalin16** [comment]
I modified the issues you mentioned yesterday. Please let me know if you have any comments or suggestions about this version. Thank you!

**Comment by christophertull** [comment]
Thanks @fangshulin! I have just a couple of comments.

Looks like the utility names are still hard-coded. It should be possible to get a dynamic list of utility names by looking at the names of the directories holding the OWRS files. e.g. "Alameda County Water District - 28/03-01-2017.owrs" you could just extract the first part from the string to get the name "Alameda County Water District". If you generate this name list in a new file `global.R` then it will execute first before the app UI is created. I think this is the last thing we need to get out of the way before moving on to issue #4!

**Comment by christophertull** [comment]
Oh, one more thing. It looks like you deleted the old files first before committing the modified files. Is there a reason for this? Generally it is good practice to commit just the changes between each version of a file rather than deleting and re-adding as if the file were new.

**Comment by christophertull** [comment]
I also pushed a small update to change the logo

**Comment by emmalin16** [comment]
Thank you for the comments! Sorry about deleting the files yesterday. There was an error when I tried to pull the files, so I used website interface and forgot to keep track of the files. There are many owrs files used tier_starts_commodity instead of tier_starts. I am wondering why different variable names are used. Do I need to make it compatible in the app? Thank you!

**Comment by emmalin16** [comment]
By the way, the error when I tried to git pull is like below. 

The following untracked working tree files would be overwritten or merged.
.gitignore
Please move or remove them before you merge. 

I haven’t figure out how to deal with it. Do you happens to know why I kept getting that error? Thank you!

**Comment by christophertull** [comment]
That means that you have edited your local `.gitignore` file so that it is different from the `.gitignore` on the server. 

If the changes to your local file are NOT important, then you can just `git checkout -- .gitignore` to reset the changes in your working directory.

If they ARE important, then you can 
```bash
git stash save
git pull
git stash pop
```
This temporarily hides your changes ("stashes" them) and then reapplies them after the pull.


For the OWRS files, `tier_starts` is in the older files that we wrote by hand. `tier_starts_commodity` is present in some of the newer files written using our survey tool. `RateParser` should be able to handle both so I don't think it should be a problem but please let me know if it is!

**Comment by emmalin16** [comment]
Thank you for the reply! 
For the OWRS files with tier_starts_commodity, I kept getting an error of _The field tier_starts is not present in the OWRS file for customer class RESIDENTIAL_SINGLE_ when using RateParser.

**Comment by christophertull** [comment]
My apologies! I thought I had integrated this code into `RateParser` but I haven't. If you use this function below to standardize the OWRS files before passing to `RateParser::calculate_bills` then it should work.

```r
standardize_OWRS_names <- function(owrs_file, current_class){
  mask <- names(owrs_file$rate_structure[[current_class]]) == "tier_starts_commodity"
  names(owrs_file$rate_structure[[current_class]])[mask] <- "tier_starts"
  
  mask <- names(owrs_file$rate_structure[[current_class]]) == "tier_prices_commodity"
  names(owrs_file$rate_structure[[current_class]])[mask] <- "tier_prices"
  
  mask <- names(owrs_file$rate_structure[[current_class]]) == "flat_rate_commodity"
  names(owrs_file$rate_structure[[current_class]])[mask] <- "flat_rate"
  
  if(owrs_file$rate_structure[[current_class]]$commodity_charge == "flat_rate_commodity*usage_ccf"){
    owrs_file$rate_structure[[current_class]]$commodity_charge <- "flat_rate*usage_ccf"
  }
  
  owrs_file$rate_structure[[current_class]]$fixed_drought_surcharge <- NULL
  owrs_file$rate_structure[[current_class]]$variable_drought_surcharge <- NULL
  owrs_file$rate_structure[[current_class]]$fixed_wastewater_charge <- NULL
  owrs_file$rate_structure[[current_class]]$variable_wastewater_charge <- NULL
  
  return(owrs_file)
}
```

**Comment by emmalin16** [comment]
Thank you for the comments! 
I just uploaded a new version of the app. I used the full name of the directories for now otherwise there are districts with the same name.
Please let me know if you have any comments about it. Thank you!

**Comment by patwater** [comment]
@fangshulin I just had a great meeting with our collaborators at the CA-Nevada section of the American Water Works Association. That's a premier industry association and we're working with them on their 2017 rate survey. 

Lots of excitement for this generalized bill calculator! Great progress and really looking forward to getting this into production to showcase your great work! 👍

**Comment by emmalin16** [comment]
@patwater Glad to hear that :) Thank you!
