### ISSUE TITLE
Address lookup to identify water agency that serves user

### ISSUE THREAD

**Issue by christophertull** [California-Data-Collaborative/BillCalculator#4]
While #3 will enable users to specify their water district to see their rates, ideally users will not need to know what water district serves them. Users should be able to enter their address and we will geocode this address, map it to a water district, and then calculate the rates.

- [x]  Add UI element to input address
- [x]  Geocode address to get lat/lons
- [x]  Map lat/lon to water district. We might needs a separate web service to enable this.

**Comment by emmalin16** [comment]
@christophertull I uploaded some preliminary result of #4. Please let me know if you have any comments. (I am using ggmap now and may cause an error if it exceeds request limits of Google maps geocoding API.)

**Comment by patwater** [comment]
Yeah that should be fine with current limits for the time being. We can move to a paid Google maps geocoding plan when we move to production

**Comment by christophertull** [comment]
Yeah, we get 2500 free lookups per day anyways, so unless this tool gets really popular I think we should be fine.
